/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/App/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BlogCard: typeof import('./components/BlogCard.vue')['default']
    DeleteConfirmationModal: typeof import('./components/Modals/DeleteConfirmationModal.vue')['default']
    DeleteModal: typeof import('./components/Modals/DeleteModal.vue')['default']
    EditPostModal: typeof import('./components/Modals/EditPostModal.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    PostCard: typeof import('./components/Posts/PostCard.vue')['default']
    PostCardMenu: typeof import('./components/Modals/PostCardMenu.vue')['default']
    PostForm: typeof import('./components/Posts/PostForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
