/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '//home': RouteRecordInfo<'//home', '/home', Record<never, never>, Record<never, never>>,
    '//my-posts': RouteRecordInfo<'//my-posts', '/my-posts', Record<never, never>, Record<never, never>>,
    '//new-post': RouteRecordInfo<'//new-post', '/new-post', Record<never, never>, Record<never, never>>,
    '//post/': RouteRecordInfo<'//post/', '/post', Record<never, never>, Record<never, never>>,
    '//post/[id]': RouteRecordInfo<'//post/[id]', '/post/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
